In [1]:
from Models.LoadAndTrainModels import *

In [2]:
def applyFeatureSetToBigrams(input_data):
    featuresets = [(sentiment_feature_bigram(bigram)) for bigram in input_data]
    return featuresets

def printProbabilitiesFromLogProb(prob_classify_dict):
    positive = prob_classify_dict["positive"]
    negative = prob_classify_dict["negative"]

    print("positive negative log: ", positive)
    print("negative negative log: ", negative)
    
    probs = np.exp([positive, negative])/np.exp([positive, negative]).sum()
    print("positive probability: ", probs[0])
    print("negative probability: ", probs[1])
    
def getProbabilitiesFromLogProb(prob_classify_dict):
    positive = prob_classify_dict["positive"]
    negative = prob_classify_dict["negative"]
    
    probs = np.exp([positive, negative])/np.exp([positive, negative]).sum()
    
    return(probs)

In [3]:
from Models import LoadAndTrainModels
from Make_Enron_Corpus import enronCorpus
from analyze_data.Data_Utils import *
from getExternalDatasets import *
data_path = os.path.join('/home/brf97486/finalProject/labelled_sentence_data_set/sentiment labelled sentences')
yelp = os.path.join(data_path, 'yelp_labelled.txt')
imdb = os.path.join(data_path, 'imdb_labelled.txt')
amazon = os.path.join(data_path, 'amazon_cells_labelled.txt')
assert os.path.isfile(yelp) 
assert os.path.isfile(imdb) 
assert os.path.isfile(amazon) 
file = open(yelp, 'r')
file2 = open(imdb, 'r')
file3 = open(amazon, 'r')
dataset = []
for line in file:
    dataset.append(re.split(r'\t+', line))
for line in file2:
    dataset.append(re.split(r'\t+', line))
for line in file3:
    dataset.append(re.split(r'\t+', line))

#dataset = [(strs, int(value)) for (strs, value) in dataset]

In [4]:
ds = []
#nltk.bigram(dataset)
for line in dataset:
    value = int(line[1])
    words = nltk.word_tokenize(line[0])
    bigram = list(nltk.bigrams(words))
    for bi in bigram:
       ds.append((bi, value)) 

In [5]:
def classifyBigramUCIDataset():
    
    print("get bigrams of common nouns and their adjectives")
    b = getBigramsOfCommonNounsAndTheirAdjective(enronCorpus())
    
    print("train classifier")
    #get the trained sentiment classifier
    classifier = LoadAndTrainModels.getNaiveBayesTrainedClassifier(getUCIDataset_bigram)

    #classify each relationship type and store the average in a dict
    avg_sentiment = {}
        
    print("average sentiment for each relation type: ", avg_sentiment)
    
    print("classifying: very good")
    prob_classify_dict = (classifier.prob_classify({"word_1":"very", 'word_2':'good'}))._prob_dict
    printProbabilitiesFromLogProb(prob_classify_dict)
    
    print("classifying: not bad")
    prob_classify_dict = (classifier.prob_classify({"word":"not bad"}))._prob_dict
    printProbabilitiesFromLogProb(prob_classify_dict)
          
    print("classifying: very envious")
    prob_classify_dict = (classifier.prob_classify({"word":"very envious"}))._prob_dict
    printProbabilitiesFromLogProb(prob_classify_dict)
    
    return classifier
    

In [6]:
classifier = classifyBigramUCIDataset()

get bigrams of common nouns and their adjectives
train classifier
Classifier accuracy percent:  64.77422762080802
average sentiment for each relation type:  {}
classifying: very good
positive negative log:  -0.41243189458133145
negative negative log:  -2.0078451690325707
positive probability:  0.8313763503641509
negative probability:  0.16862364963584903
classifying: not bad
positive negative log:  -0.9970503833901754
negative negative log:  -1.0029556595123
positive probability:  0.5014763147403278
negative probability:  0.4985236852596722
classifying: very envious
positive negative log:  -0.9970503833901754
negative negative log:  -1.0029556595123
positive probability:  0.5014763147403278
negative probability:  0.4985236852596722


In [7]:
print("classifying: very good")
prob_classify_dict = (classifier.prob_classify({"word_1":"thanks", "word_2":"mike"}))._prob_dict
printProbabilitiesFromLogProb(prob_classify_dict)

classifying: very good
positive negative log:  -1.000761134641202
negative negative log:  -0.9992392667052066
positive probability:  0.4996195330894339
negative probability:  0.5003804669105661


In [8]:
train, test, prop = getUCIDataset_bigram()

In [9]:
b = getBigramsOfCommonNounsAndTheirAdjective(enronCorpus())

In [10]:
from Make_Enron_Corpus import enronCorpus
avg_sentiment = {}

In [11]:
#get a list of probabilites for each bigarm in each fileid
for d in enron_corp.fileids():
        
        input_data = b[d]
        relation_bigram_feature_data = LoadAndTrainModels.applyFeatureSetToTaggedBigrams(input_data, only_nouns_and_adj=True) 
        
        if(len(relation_bigram_feature_data) == 0):
            avg_sentiment[d] = [[0,0]]
        else:
            avg_sentiment[d] = []
            #total_sentiment = 0
            for feature in relation_bigram_feature_data:               
                prob_classify_dict = classifier.prob_classify(feature)._prob_dict
                avg_sentiment[d].append(getProbabilitiesFromLogProb(prob_classify_dict))

ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
N

ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
A

NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
N

ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
N

NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
N

NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
N

ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
A

ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
A

ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
A

ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
NOUN
ADJ
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
NOUN
ADJ
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
A

ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
NOUN
ADJ
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
NOUN
ADJ
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
A

NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
N

ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
NOUN
ADJ
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
ADJ
NOUN
N

In [15]:
print("file    likelihood that file is all positive")
for file in avg_sentiment:
    #print(file)
    avg_a_prediction_for_extremes = 0
    total_prediction_for_extremes = 0
    count = 0
    
    arr = avg_sentiment[file]
    for a in arr:
        if(a[0] > .6 or a[0] < .4):
            total_prediction_for_extremes += a[0]
            count += 1
    avg_a_prediction_for_extremes = total_prediction_for_extremes/count
    print(file, " : ", avg_a_prediction_for_extremes)

file    likelihood that file is all positive
5_5.txt  :  0.5253944718334358
5_2.txt  :  0.6466769186122123
2_1.txt  :  0.475497822822515
4_5.txt  :  0.5732970668028936
4_2.txt  :  0.4721795492261291
5_3.txt  :  0.5264121473365168
5_4.txt  :  0.5591614009789072
1_1.txt  :  0.5273326230642792
4_4.txt  :  0.5918537444253293
1_5.txt  :  0.5207684108987786
1_2.txt  :  0.5156865242986824
3_3.txt  :  0.0
2_4.txt  :  0.4895623788743171
4_1.txt  :  0.49746103589700447
3_2.txt  :  0.5123712779348623
3_5.txt  :  0.22118910544482195
1_4.txt  :  0.44849319352700495
5_1.txt  :  0.4134810543853693
2_2.txt  :  0.518445888549497
2_5.txt  :  0.5141483569884204


In [13]:
avg_sentiment

{'5_5.txt': [array([0.55499425, 0.44500575]),
  array([0.28732481, 0.71267519]),
  array([0.73075926, 0.26924074]),
  array([0.73075926, 0.26924074]),
  array([0.73075926, 0.26924074]),
  array([0.73075926, 0.26924074]),
  array([0.73075926, 0.26924074]),
  array([0.73075926, 0.26924074]),
  array([0.73075926, 0.26924074]),
  array([0.73075926, 0.26924074]),
  array([0.19964014, 0.80035986]),
  array([0.49961953, 0.50038047]),
  array([0.82969124, 0.17030876]),
  array([0.73075926, 0.26924074]),
  array([0.73075926, 0.26924074]),
  array([0.49961953, 0.50038047]),
  array([0.11904323, 0.88095677]),
  array([0.49961953, 0.50038047]),
  array([0.51071642, 0.48928358]),
  array([0.49961953, 0.50038047]),
  array([0.11904323, 0.88095677]),
  array([0.49961953, 0.50038047]),
  array([0.51071642, 0.48928358]),
  array([0.19964014, 0.80035986]),
  array([0.49961953, 0.50038047]),
  array([0.82969124, 0.17030876]),
  array([0.73075926, 0.26924074]),
  array([0.73075926, 0.26924074]),
  array([

In [14]:
for x in classifier._feature_probdist:
    print(x)

('positive', 'word_1')
('positive', 'word_2')
('negative', 'word_1')
('negative', 'word_2')
