In [1]:
import numpy as np

from Models import LoadAndTrainModels
from Make_Enron_Corpus import enronCorpus
from analyze_data.Data_Utils import *
from getExternalDatasets import *

def printProbabilitiesFromLogProb(prob_classify_dict):
    positive = prob_classify_dict["positive"]
    negative = prob_classify_dict["negative"]

    print("positive negative log: ", positive)
    print("negative negative log: ", negative)
    
    probs = np.exp([positive, negative])/np.exp([positive, negative]).sum()
    print("positive probability: ", probs[0])
    print("negative probability: ", probs[1])
    
def getProbabilitiesFromLogProb(prob_classify_dict):
    positive = prob_classify_dict["positive"]
    negative = prob_classify_dict["negative"]
    
    probs = np.exp([positive, negative])/np.exp([positive, negative]).sum()
    
    return(probs)

In [2]:
def classifySentenceUCIDataset():
    train_data, test_data, prob = getUCIDataset_sentences()
    #get the trained sentiment classifier
    print("load and train model")
    classifier = LoadAndTrainModels.getNaiveBayesTrainedClassifier(getUCIDataset_sentences)
    
    print("building enron corpus")
    enron_corp = enronCorpus()
    
    avg_sentiment = {}
    
    
    file_list = ['4_5.txt',
'4_2.txt',
'5_3.txt',
'5_4.txt',
'1_1.txt',
'4_4.txt',
'1_5.txt',
'1_2.txt',
'2_4.txt',
'4_1.txt',
'3_2.txt',
'3_5.txt',
'1_4.txt',
'5_1.txt',
'2_2.txt',
'2_5.txt']
    
    print("apply features and sentiments")
    for d in enron_corp.fileids():
        break
        #input_data = enron_corp.sentences(d)
        input_data = (enronCorpus().raw()).split('.')
        relation_sentence_feature_data = LoadAndTrainModels.applyFeatureSetToSentence(input_data)
        total_sentiment = 0
        total_sentiment = classifier.classify_many(featuresets=relation_sentence_feature_data)
        avg_sentiment[d] = sum(total_sentiment)/len(relation_sentence_feature_data)
        print(d, " complete...")
        print(avg_sentiment)
        #break
    print("average sentiment for each relation type: ", avg_sentiment)

In [3]:
#classifySentenceUCIDataset()

In [4]:
classifier = LoadAndTrainModels.getNaiveBayesTrainedClassifier(getUCIDataset_sentences)

Classifier accuracy percent:  67.66666666666666


In [16]:
#3=>5
sentence = 'the cob sn np buy resale that will screw up our position'
sentence_with_features = sentiment_feature_sentence(sentence)
printProbabilitiesFromLogProb(classifier.prob_classify(sentence_with_features)._prob_dict)

positive negative log:  -1.3356068364691538
negative negative log:  -0.7279179577443031
positive probability:  0.3525865760070904
negative probability:  0.6474134239929096


In [21]:
#5=>4
sentence = 'the entire country will soon be short on power'
sentence_with_features = sentiment_feature_sentence(sentence)
printProbabilitiesFromLogProb(classifier.prob_classify(sentence_with_features)._prob_dict)

positive negative log:  -1.6873487151073903
negative negative log:  -0.5363712887599732
positive probability:  0.24031059742432956
negative probability:  0.7596894025756704


In [24]:
#4=>4 
sentence = 'all broker deal will be handled this way'
sentence_with_features = sentiment_feature_sentence(sentence)
printProbabilitiesFromLogProb(classifier.prob_classify(sentence_with_features)._prob_dict)

positive negative log:  -1.081456270348518
negative negative log:  -0.9228980895709284
positive probability:  0.4604432936976482
negative probability:  0.5395567063023518


In [30]:
#5=>3 positive
sentence = 'good morning these are the position that i see for february please take a look at them and let me know if you agree or not.'
sentence_with_features = sentiment_feature_sentence(sentence)
printProbabilitiesFromLogProb(classifier.prob_classify(sentence_with_features)._prob_dict)

positive negative log:  -0.1714616574534702
negative negative log:  -3.157690322623033
positive probability:  0.9519480920155345
negative probability:  0.04805190798446543


In [6]:
classifier.show_most_informative_features()

Most Informative Features
            adjAfterNoun = 'bad'          negati : positi =     15.4 : 1.0
                fistVerb = 'love'         positi : negati =     12.2 : 1.0
           adjBeforeNoun = 'bad'          negati : positi =      9.8 : 1.0
            adjAfterNoun = 'great'        positi : negati =      9.1 : 1.0
            adjAfterNoun = 'terrible'     negati : positi =      8.2 : 1.0
           adjBeforeNoun = 'best'         positi : negati =      7.3 : 1.0
                fistVerb = 'Do'           negati : positi =      5.5 : 1.0
               firstNoun = 'hour'         negati : positi =      4.6 : 1.0
                fistVerb = 'recommend'    positi : negati =      4.4 : 1.0
            adjAfterNoun = 'best'         positi : negati =      4.4 : 1.0


In [7]:
classifier._labels

['positive', 'negative']

In [8]:
all_tagged_sents = {}

for d in enron_corp.fileids():
    all_tagged_sents[d] = getTaggedFile(enron_corp, d)
    

In [9]:
avg_sentiment = {}

In [10]:
for d in enron_corp.fileids():
    input_data = all_tagged_sents[d] #a file's tagged sentences
    
    relation_sentence_feature_data = LoadAndTrainModels.applyFeatureSetToTaggedSentence(input_data)
        
    if(len(relation_sentence_feature_data) == 0):
        avg_sentiment[d] = [[0,0]]
    else:
        avg_sentiment[d] = []
        #total_sentiment = 0
        for feature in relation_sentence_feature_data:               
            prob_classify_dict = classifier.prob_classify(feature)._prob_dict
            avg_sentiment[d].append(getProbabilitiesFromLogProb(prob_classify_dict))

In [11]:
avg_sentiment

{'5_5.txt': [array([0.13616839, 0.86383161]),
  array([0.22196374, 0.77803626]),
  array([0.40369542, 0.59630458]),
  array([0.95496895, 0.04503105]),
  array([0.27846122, 0.72153878]),
  array([0.82787662, 0.17212338]),
  array([0.1986377, 0.8013623]),
  array([0.40369542, 0.59630458]),
  array([0.63891375, 0.36108625]),
  array([0.1986377, 0.8013623]),
  array([0.40369542, 0.59630458]),
  array([0.63891375, 0.36108625]),
  array([0.1986377, 0.8013623]),
  array([0.40369542, 0.59630458]),
  array([0.63891375, 0.36108625]),
  array([0.1986377, 0.8013623]),
  array([0.40369542, 0.59630458]),
  array([0.63891375, 0.36108625]),
  array([0.42045584, 0.57954416]),
  array([0.79095696, 0.20904304]),
  array([0.15870138, 0.84129862]),
  array([0.72834237, 0.27165763]),
  array([0.42569707, 0.57430293]),
  array([0.79095696, 0.20904304]),
  array([0.15870138, 0.84129862]),
  array([0.72834237, 0.27165763]),
  array([0.42045584, 0.57954416]),
  array([0.79095696, 0.20904304]),
  array([0.158701

In [12]:
print("file    likelihood that file is all positive")
for file in avg_sentiment:
    #print(file)
    avg_a_prediction_for_extremes = 0
    total_prediction_for_extremes = 0
    count = 0
    
    arr = avg_sentiment[file]
    for a in arr:
        if(a[0] > .6 or a[0] < .4):
            total_prediction_for_extremes += a[0]
            count += 1
    avg_a_prediction_for_extremes = total_prediction_for_extremes/count
    print(file, " : ", avg_a_prediction_for_extremes)

file    likelihood that file is all positive
5_5.txt  :  0.49432016448250654
5_2.txt  :  0.4812863914896426
2_1.txt  :  0.45433481899315287
4_5.txt  :  0.5282385703321014
4_2.txt  :  0.47669908929855437
5_3.txt  :  0.5833768493441586
5_4.txt  :  0.3962789114654197
1_1.txt  :  0.4678397633191489
4_4.txt  :  0.5898662076228002
1_5.txt  :  0.4651639152589174
1_2.txt  :  0.47865444288582953
3_3.txt  :  0.0
2_4.txt  :  0.47820311339720395
4_1.txt  :  0.4360524088616735
3_2.txt  :  0.498648177475332
3_5.txt  :  0.3280887761379842
1_4.txt  :  0.4777584405913372
5_1.txt  :  0.4508305590651652
2_2.txt  :  0.45237727994686133
2_5.txt  :  0.5067684717794985
